version: '3.5'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: diagnostic
      POSTGRES_PASSWORD: 123
    ports:
    - 5432:5432
  api:
    build: .
    environment:
      APP_SETTINGS: "project.server.config.ProductionConfig"
    ports:
    - 8080:8080